# Generated by Django 4.0 on 2022-01-08 23:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('priority', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bug_tickets',
            },
        ),
        migrations.CreateModel(
            name='SortedBugTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_ref', models.IntegerField()),
                ('bug_priority', models.IntegerField()),
            ],
            options={
                'db_table': 'sorted_bug_Tickets',
            },
            managers=[
                ('chandiyo', django.db.models.manager.Manager()),
            ],
        ),
    ]
