# Generated by Django 4.0 on 2022-01-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bugtickets',
            table='Bug_Tickets',
        ),
    ]
