# Generated by Django 4.0 on 2022-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bugtickets_date_alter_bugtickets_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtickets',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
