# Generated by Django 4.0 on 2022-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_bugtickets_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugtickets',
            old_name='date',
            new_name='create_date',
        ),
        migrations.AddField(
            model_name='bugtickets',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
