# Generated by Django 4.0 on 2022-01-07 18:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_bugtickets_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedBugTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_ref', models.IntegerField()),
                ('bug_priority', models.IntegerField()),
            ],
            options={
                'db_table': 'sorted_bug_Tickets',
            },
            managers=[
                ('chandiyo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelTable(
            name='bugtickets',
            table='bug_tickets',
        ),
    ]
